//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TreeNodes.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class kunsaa_Entities : DbContext
    {
        public kunsaa_Entities()
            : base("name=kunsaa_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Node> Nodes { get; set; }
        public DbSet<PERSON> PERSONS { get; set; }
    
        public virtual ObjectResult<GetNodeInfo_Result> GetNodeInfo()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetNodeInfo_Result>("GetNodeInfo");
        }
    }
}
