//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TreeNodes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Node
    {
        public int nodeId { get; set; }
        public string nodeName { get; set; }
        public Nullable<int> ParentNodeId { get; set; }
        public bool isActive { get; set; }
        public System.DateTime StartDate { get; set; }
    }
}
